app = "crisp-qes-web"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    VITE_CHAIN_ID = "84532"
    VITE_RPC_URL = "https://sepolia.base.org"
    VITE_REGISTRY_ADDRESS = "0x86c986f361ddb447949bf010a3f01e0b5a97fbc0"
    VITE_RELAYER_URL = "https://crisp-qes-relayer.fly.dev"
    VITE_TRUST_MANIFEST_URL = "/trust-manifest.json"
    VITE_CIRCUIT_URL = "/crisp_qes_circuit.json"
    VITE_BLOCK_EXPLORER = "https://sepolia.basescan.org"
    VITE_WALLETCONNECT_PROJECT_ID = "33a263ffda20d72b289cf92b369cfa47"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
